
stages:
  - compile
  - test
  - lint

variables:
  DOCKER_HOST: tcp://docker:2375

build:
  stage: compile
  image: tmaier/docker-compose:latest
  services:
    - docker:dind
  before_script:
    - docker info
    - docker-compose --version
  script:
    - cp .env-example .env
    - docker-compose build
test:
  stage: test
  image: tmaier/docker-compose:latest
  services:
    - docker:dind
  before_script:
    - docker info
    - docker-compose --version
  script:
    - cp .env-example .env
    - docker-compose up -d 
    - docker-compose ps 
    - docker-compose run api go test tests/*.go -v 
lint:
  stage: lint
  image: golang:latest
  before_script:
    - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s latest
    - mv ./bin/golangci-lint /usr/local/bin/
  script:
    - golangci-lint run --timeout 10m